"""avatar_field

Revision ID: 027e46c7265a
Revises: 9174b9d42ddc
Create Date: 2022-02-05 20:30:24.402906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027e46c7265a'
down_revision = '9174b9d42ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
