"""prefetch_posts_users

Revision ID: 08311e690034
Revises: a3926e179f42
Create Date: 2022-01-27 15:41:32.958680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08311e690034'
down_revision = 'a3926e179f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
