"""avatar_field

Revision ID: 9174b9d42ddc
Revises: b90762fd097e
Create Date: 2022-02-05 20:29:46.938440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9174b9d42ddc'
down_revision = 'b90762fd097e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_avatar'), 'users', ['avatar'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_avatar'), table_name='users')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
